- name: Create directory for docker project
  ansible.builtin.file:
    path: "/{{deploy_docker_project_directory}}/automation/{{deploy_docker_project_name}}"
    state: directory
    recurse: yes

- name: Deploy docker compose file
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "/{{deploy_docker_project_directory}}/automation/{{deploy_docker_project_name}}/compose.yaml"

- name: Login to docker registry
  community.docker.docker_login:
    registry: "{{ deploy_docker_registry_addr }}:{{ deploy_docker_registry_port }}"
    username: "{{ deploy_docker_registry_username }}"
    password: "{{ deploy_docker_registry_token }}"
    reauthorize: true
    state: present

- name: Deploy docker project
  community.docker.docker_compose_v2:
    project_src: "/{{deploy_docker_project_directory}}/automation/{{deploy_docker_project_name}}"
    pull: always
    recreate: always
    remove_orphans: true
    remove_volumes: true
    wait: true
    wait_timeout: 180