---
    - name: Update Debian system(s)
      hosts: debian
      become: true
      gather_facts: false
      tasks:
        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600
    
        - name: Upgrade package(s)
          ansible.builtin.apt:
            upgrade: dist
            force_apt_get: yes
    
        - name: Remove obsolete package(s)
          ansible.builtin.apt:
            autoremove: yes
            purge: yes
    
        - name: Clean apt cache
          ansible.builtin.apt:
            autoclean: yes

    - name: Update Alpine system(s)
      hosts: alpine
      become: true
      gather_facts: false
      tasks:
        - name: Update apk cache
          ansible.builtin.apk:
            update_cache: yes

        - name: Upgrade package(s)
          ansible.builtin.apk:
            upgrade: yes

    - name: Update Windows system(s)
      hosts: windows
      gather_facts: false
      tasks:
        - name: Check for Windows updates
          ansible.windows.win_updates:
            category_names:
              - SecurityUpdates
              - CriticalUpdates
              - UpdateRollups
              - Updates
              - DefinitionUpdates
            state: installed
            reboot: yes
          register: update_result

        - name: Reboot if needed
          ansible.windows.win_reboot:
          when: update_result.reboot_required
