services:
  python:
    restart: no
    image: ghcr.io/nicolas-mahe/ansible-home:${DOCKER_TAG:-main}
    container_name: ansible-home
    hostname: ansible-home
    environment:
      TZ: Europe/Paris
      ANSIBLE_VERBOSITY: ${ANSIBLE_VERBOSITY:-1}
    volumes:
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/ansible-home/inventories:/inventories:ro
      - /${DOCKER_DATA_DIRECTORY:?data path is required}/docker/docker-data/ansible-home/.vault:/.vault:ro
