services:
  python:
    restart: no
    image: ghcr.io/nicolas-mahe/ansible-home:${DOCKER_TAG:-main}
    container_name: ansible-home
    hostname: ansible-home
    environment:
      TZ: Europe/Paris
      ANSIBLE_VERBOSITY: ${ANSIBLE_VERBOSITY:-1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ANSIBLE_SSH_KEY_DIRECTORY:?ssh key path is required}:/ansible/.id_rsa:ro
      - ${ANSIBLE_VAULT_DIRECTORY:?vault path is required}:/ansible/.vault:ro
